version: '3.4'

services:
  tecnicovismaapi:
    image: ${DOCKER_REGISTRY-}tecnicovismaapi
    build:
      context: .
      dockerfile: TecnicoVismaAPI/Dockerfile

  tecnicovismaui:
    image: ${DOCKER_REGISTRY-}tecnicovismaui
    build: 
      context: .
      dockerfile: ../TecnicoVismaUI/Dockerfile