version: '3.4'

volumes:
  datafiles:

services:

  database:
    image: mysql:8.0.0
    container_name: TecnicoVismaMySQL
    command: --skip-ssl
    ports:
      - "3305:3306"
    restart: always
    volumes:
      - datafiles:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: '123456'
        MYSQL_DATABASE: TecnicoVismaDB
    networks:
      - backend
     
  tecnicovismaui:
    build:
      dockerfile: ${DOCKERFILE}
      context: ../TecnicoVismaUI
    container_name: TecnicoVismaUI
    hostname: tecnicovismaui   
    depends_on:
      - tecnicovismaapi
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "4200:80"
    networks:
      - frontend
      
  tecnicovismaapi:
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
        database:
          condition: service_started
    links:
      - database
    restart: on-failure
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - backend
      
      
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge


